'use client';

import { useEffect, useState } from 'react';
import { api, relativeTime } from '@/lib/api';
type SecurityData = { setupScore: number; twoFactorEnabled: boolean; sessions: Array<{ _id: string; device: string; ip: string; lastActivityAt: string }>; events: Array<{ _id: string; type: string; severity: string; createdAt: string }> };
export default function SecurityPage() {
  const [data, setData] = useState<SecurityData>();
  const [error, setError] = useState('');
  useEffect(() => { void api<SecurityData>('/security/overview').then(setData).catch((reason: Error) => setError(reason.message)); }, []);
  return <><header className="page-header"><div><p className="eyebrow">Protect your account</p><h1 className="page-title">Security center</h1><p className="page-subtitle">Review active sessions, two-factor status, and recent alerts.</p></div></header>{error && <div className="notice error" role="alert">{error}</div>}{!data ? <div className="skeleton" /> : <><section className="stats-grid"><article className="stat-card"><div className="stat-top">Security setup score</div><p className="stat-value">{data.setupScore}%</p></article><article className="stat-card"><div className="stat-top">Two-factor authentication</div><p className="stat-value">{data.twoFactorEnabled ? 'On' : 'Off'}</p></article><article className="stat-card"><div className="stat-top">Active sessions</div><p className="stat-value">{data.sessions.length}</p></article><article className="stat-card"><div className="stat-top">Recent alerts</div><p className="stat-value">{data.events.length}</p></article></section><section className="panel"><h2>Security events</h2>{data.events.length === 0 ? <div className="empty-state"><p>No security alerts.</p></div> : data.events.map((event) => <div className="activity-row" key={event._id}><span className="activity-line" /><span><strong>{event.type.replaceAll('_', ' ')}</strong><small>{event.severity}</small></span><small>{relativeTime(event.createdAt)}</small></div>)}</section><section className="panel"><h2>Active sessions</h2>{data.sessions.map((session) => <div className="setting-row" key={session._id}><span><strong>{session.device}</strong><p>{session.ip} · {relativeTime(session.lastActivityAt)}</p></span><button className="button danger" onClick={() => void api(`/auth/sessions/${session._id}`, { method: 'DELETE' }).then(() => setData({ ...data, sessions: data.sessions.filter((item) => item._id !== session._id) })).catch((reason: Error) => setError(reason.message))}>Revoke</button></div>)}</section></>}</>;
}
