export const AUDIT_ACTIONS = [
  'LOGIN_SUCCESS', 'LOGIN_FAILED', 'FILE_UPLOADED', 'FILE_VIEWED', 'FILE_DOWNLOADED',
  'FILE_RENAMED', 'FILE_MOVED', 'FILE_DELETED', 'FILE_RESTORED', 'FILE_VERSION_CREATED',
  'SHARE_CREATED', 'SHARE_ACCESSED', 'SHARE_REVOKED', 'SHARE_EXPIRED',
  'SHARE_PASSWORD_FAILED', 'MEMBER_INVITED', 'ROLE_CHANGED', 'TWO_FACTOR_ENABLED',
  'TWO_FACTOR_DISABLED'
] as const;

export const SECURITY_EVENT_TYPES = [
  'MULTIPLE_LOGIN_FAILURES', 'NEW_DEVICE_LOGIN', 'SHARE_BRUTE_FORCE', 'EXCESSIVE_DOWNLOADS',
  'SUSPICIOUS_SHARE_ACCESS', 'MALWARE_DETECTED', 'RATE_LIMIT_TRIGGERED', 'SESSION_TOKEN_REUSE',
  'UNAUTHORIZED_ACCESS_ATTEMPT'
] as const;

export const apiError = (code: string, message: string, requestId: string) => ({
  success: false as const,
  error: { code, message, requestId }
});
